// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: company.proto
// Protobuf C++ Version: 7.34.1

#ifndef company_2eproto_2epb_2eh
#define company_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_company_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_company_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_company_2eproto;
}  // extern "C"
class Company;
struct CompanyDefaultTypeInternal;
extern CompanyDefaultTypeInternal _Company_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Company_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED Company final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Company) */ {
 public:
  inline Company() : Company(nullptr) {}
  ~Company() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Company* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Company));
  }
#endif

  template <typename = void>
  explicit constexpr Company(::google::protobuf::internal::ConstantInitialized);

  inline Company(const Company& from) : Company(nullptr, from) {}
  inline Company(Company&& from) noexcept
      : Company(nullptr, ::std::move(from)) {}
  inline Company& operator=(const Company& from) {
    CopyFrom(from);
    return *this;
  }
  inline Company& operator=(Company&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const Company& default_instance() {
    return *reinterpret_cast<const Company*>(
        &_Company_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Company& a, Company& b) { a.Swap(&b); }
  inline void Swap(Company* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Company* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] Company* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Company>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Company& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Company& from) { Company::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Company* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Company"; }

  explicit Company(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Company(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Company& from);
  Company(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Company&& from) noexcept
      : Company(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameCompanyFieldNumber = 1,
    kLegalAddressFieldNumber = 3,
    kOccupationCompanyFieldNumber = 4,
    kYearCreatedFieldNumber = 2,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string NameCompany = 1;
  [[nodiscard]] bool has_namecompany()
      const;
  void clear_namecompany() ;
  [[nodiscard]] const ::std::string& namecompany() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_namecompany(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_namecompany();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_namecompany();
  void set_allocated_namecompany(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_namecompany() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_namecompany(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_namecompany();

  public:
  // required string LegalAddress = 3;
  [[nodiscard]] bool has_legaladdress()
      const;
  void clear_legaladdress() ;
  [[nodiscard]] const ::std::string& legaladdress() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_legaladdress(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_legaladdress();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_legaladdress();
  void set_allocated_legaladdress(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_legaladdress() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_legaladdress(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_legaladdress();

  public:
  // optional string OccupationCompany = 4;
  [[nodiscard]] bool has_occupationcompany()
      const;
  void clear_occupationcompany() ;
  [[nodiscard]] const ::std::string& occupationcompany() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_occupationcompany(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_occupationcompany();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_occupationcompany();
  void set_allocated_occupationcompany(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_occupationcompany() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_occupationcompany(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_occupationcompany();

  public:
  // required int32 YearCreated = 2;
  [[nodiscard]] bool has_yearcreated()
      const;
  void clear_yearcreated() ;
  [[nodiscard]] ::int32_t yearcreated() const;
  void set_yearcreated(::int32_t value);

  private:
  ::int32_t _internal_yearcreated() const;
  void _internal_set_yearcreated(::int32_t value);

  public:
  // optional bool foreignEconomicActivity = 5;
  [[nodiscard]] bool has_foreigneconomicactivity()
      const;
  void clear_foreigneconomicactivity() ;
  [[nodiscard]] bool foreigneconomicactivity() const;
  void set_foreigneconomicactivity(bool value);

  private:
  bool _internal_foreigneconomicactivity() const;
  void _internal_set_foreigneconomicactivity(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Company)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Company& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr namecompany_;
    ::google::protobuf::internal::ArenaStringPtr legaladdress_;
    ::google::protobuf::internal::ArenaStringPtr occupationcompany_;
    ::int32_t yearcreated_;
    bool foreigneconomicactivity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_company_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Company_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Company

// required string NameCompany = 1;
inline bool Company::has_namecompany() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Company::clear_namecompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namecompany_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Company::namecompany() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Company.NameCompany)
  return _internal_namecompany();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Company::set_namecompany(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.namecompany_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Company.NameCompany)
}
inline ::std::string* PROTOBUF_NONNULL Company::mutable_namecompany()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_namecompany();
  // @@protoc_insertion_point(field_mutable:Company.NameCompany)
  return _s;
}
inline const ::std::string& Company::_internal_namecompany() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.namecompany_.Get();
}
inline void Company::_internal_set_namecompany(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namecompany_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Company::_internal_mutable_namecompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.namecompany_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Company::release_namecompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Company.NameCompany)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.namecompany_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.namecompany_.Set("", GetArena());
  }
  return released;
}
inline void Company::set_allocated_namecompany(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.namecompany_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.namecompany_.IsDefault()) {
    _impl_.namecompany_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Company.NameCompany)
}

// required int32 YearCreated = 2;
inline bool Company::has_yearcreated() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Company::clear_yearcreated() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yearcreated_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Company::yearcreated() const {
  // @@protoc_insertion_point(field_get:Company.YearCreated)
  return _internal_yearcreated();
}
inline void Company::set_yearcreated(::int32_t value) {
  _internal_set_yearcreated(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Company.YearCreated)
}
inline ::int32_t Company::_internal_yearcreated() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.yearcreated_;
}
inline void Company::_internal_set_yearcreated(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.yearcreated_ = value;
}

// required string LegalAddress = 3;
inline bool Company::has_legaladdress() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Company::clear_legaladdress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.legaladdress_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Company::legaladdress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Company.LegalAddress)
  return _internal_legaladdress();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Company::set_legaladdress(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.legaladdress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Company.LegalAddress)
}
inline ::std::string* PROTOBUF_NONNULL Company::mutable_legaladdress()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_legaladdress();
  // @@protoc_insertion_point(field_mutable:Company.LegalAddress)
  return _s;
}
inline const ::std::string& Company::_internal_legaladdress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.legaladdress_.Get();
}
inline void Company::_internal_set_legaladdress(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.legaladdress_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Company::_internal_mutable_legaladdress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.legaladdress_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Company::release_legaladdress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Company.LegalAddress)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.legaladdress_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.legaladdress_.Set("", GetArena());
  }
  return released;
}
inline void Company::set_allocated_legaladdress(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.legaladdress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.legaladdress_.IsDefault()) {
    _impl_.legaladdress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Company.LegalAddress)
}

// optional string OccupationCompany = 4;
inline bool Company::has_occupationcompany() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Company::clear_occupationcompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.occupationcompany_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& Company::occupationcompany() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Company.OccupationCompany)
  return _internal_occupationcompany();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Company::set_occupationcompany(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.occupationcompany_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Company.OccupationCompany)
}
inline ::std::string* PROTOBUF_NONNULL Company::mutable_occupationcompany()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_occupationcompany();
  // @@protoc_insertion_point(field_mutable:Company.OccupationCompany)
  return _s;
}
inline const ::std::string& Company::_internal_occupationcompany() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.occupationcompany_.Get();
}
inline void Company::_internal_set_occupationcompany(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.occupationcompany_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Company::_internal_mutable_occupationcompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.occupationcompany_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Company::release_occupationcompany() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Company.OccupationCompany)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.occupationcompany_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.occupationcompany_.Set("", GetArena());
  }
  return released;
}
inline void Company::set_allocated_occupationcompany(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.occupationcompany_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.occupationcompany_.IsDefault()) {
    _impl_.occupationcompany_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Company.OccupationCompany)
}

// optional bool foreignEconomicActivity = 5;
inline bool Company::has_foreigneconomicactivity() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Company::clear_foreigneconomicactivity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreigneconomicactivity_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool Company::foreigneconomicactivity() const {
  // @@protoc_insertion_point(field_get:Company.foreignEconomicActivity)
  return _internal_foreigneconomicactivity();
}
inline void Company::set_foreigneconomicactivity(bool value) {
  _internal_set_foreigneconomicactivity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Company.foreignEconomicActivity)
}
inline bool Company::_internal_foreigneconomicactivity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.foreigneconomicactivity_;
}
inline void Company::_internal_set_foreigneconomicactivity(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreigneconomicactivity_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // company_2eproto_2epb_2eh
